title: "Abubakar Abdullahi â€” Data Engineering"
description: "Production-like data engineering builds, explained clearly."
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Abubakar Abdullahi"
github_username: "princeabdul99"
# youtube_channel: "@dataslinger6379"
# medium_username: "dataslinger"
exclude:
  - "README.md"
